services:
  db:
    image: postgres:18
    container_name: postgres_container_dev
    environment:
      POSTGRES_USER: ${DATABASE_USERNAM}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
